-- Create a new table to store daily production goals per line, based on day of week
CREATE TABLE IF NOT EXISTS public.production_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    line CHARACTER VARYING NOT NULL,
    goal_value NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Ensure only one goal per line per day of week
    CONSTRAINT unique_day_of_week_line UNIQUE (day_of_week, line)
);

-- Add comments for documentation
COMMENT ON TABLE public.production_goals IS 'Stores daily production value goals for each production line, mapped by day of week.';
COMMENT ON COLUMN public.production_goals.day_of_week IS '0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday';
COMMENT ON COLUMN public.production_goals.line IS 'The production line identifier (e.g., A, B, C).';
COMMENT ON COLUMN public.production_goals.goal_value IS 'The target production value in dollars.';

-- Enable Row Level Security (RLS)
ALTER TABLE public.production_goals ENABLE ROW LEVEL SECURITY;

-- Simple policy for authenticated users
CREATE POLICY "Allow authenticated read access" ON public.production_goals
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated insert/update access" ON public.production_goals
    FOR ALL TO authenticated USING (true);
